export const events = [
  {
    id: "1",
    categoryId: "1",
    titleId: "1",
    date: "2023-12-4",
    startAt: "16:30",
    endAt: "17:45",
    place: "オモケンパーク",
    target: "大学生・高校生",
    maximumParticipant: 8,
    fee: 500,
    description:
      "英語で楽しくお話したい人・英語学習仲間を増やしたい人・学習しながら英語を楽しく話したい人はぜひ一度参加してみてください",
  },
  {
    id: "2",
    categoryId: "4",
    titleId: "4",
    date: "2023-12-10",
    startAt: "16:30",
    endAt: "18:30",
    place: "レンタルスペース",
    target: "大学生・高校生・ALT",
    maximumParticipant: 20,
    fee: 1500,
    description: "",
  },
  {
    id: "3",
    categoryId: "3",
    titleId: "3",
    date: "2023-12-14",
    startAt: "18:00",
    place: "https://podcasters.spotify.com/pod/show/enmove",
    target: "多文化共生に興味のある方・外国人の暮らしについて知りたい方",
    fee: 0,
    description:
      "地方で活躍する外国人コミュニティの声を通じて、彼らの生活・挑戦・夢・悩み・日常であまり聞かれることのない声をあなたにお届けします。",
  },
  {
    id: "4",
    categoryId: "1",
    titleId: "1",
    date: "2023-12-18",
    startAt: "16:30",
    endAt: "17:45",
    place: "オモケンパーク",
    target: "大学生・高校生",
    maximumParticipant: 8,
    fee: 500,
    description:
      "英語で楽しくお話したい人・英語学習仲間を増やしたい人・学習しながら英語を楽しく話したい人はぜひ一度参加してみてください",
  },
];
